
// This file was auto-generated by ML.NET Model Builder. 

using FemaleBoneAgeAI_ConsoleApp1;
using System.IO;

// Create single instance of sample data from first line of dataset for model input
var imageBytes = File.ReadAllBytes(@"C:\Users\prkna\Desktop\bone-age\data\Training\Female\10\3935.png");
FemaleBoneAgeAI.ModelInput sampleData = new FemaleBoneAgeAI.ModelInput()
{
    ImageSource = imageBytes,
};

// Make a single prediction on the sample data and print results.
var predictionResult = FemaleBoneAgeAI.Predict(sampleData);
Console.WriteLine($"\n\nPredicted Label value: {predictionResult.PredictedLabel} \nPredicted Label scores: [{String.Join(",", predictionResult.Score)}]\n\n");